version: '3'
services:
  apache:
    build: ./docker/apache
    container_name: sf4_apache
    working_dir: /application
    ports:
      - 5003:80
    volumes:
      - ./docker/config/vhosts:/etc/apache2/sites-enabled
      - ./docker/php/opcache.ini:/etc/apache2/mods-available/opcache.ini
      - ./docker/php/xdebug.ini:/etc/apache2/mods-available/xdebug.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/application
    depends_on:
      - php
    environment:
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=docker.for.mac.host.internal
  mysql:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: sf4_mysql
    working_dir: /application
    volumes:
      - ./docker/mysql/data/db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - .:/application
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ashot
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  php:
    build: ./docker/php
    container_name: sf4_php
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php/xdebug.ini:/etc/apache2/mods-available/xdebug.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - mysql
    environment:
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=docker.for.mac.host.internal

#  angular-app:
#    build: ./docker/angular-app
#    container_name: sf4_angular_app
#    volumes:
#      - ./:/application
#    working_dir: /application/public/angular-app/
#    entrypoint: ash -c 'npm install && npm run build-dev && npm run dev'
#    ports:
#      - "8080:8080"
#    networks:
#      app_nw:
#        ipv4_address: 172.21.0.9
