index:
    path: /
    controller: App\Controller\IndexController::showAction

painting_technique:
    path: /painting/technique
    controller: App\Controller\PaintingTechniqueController::showAction

elite_gift:
    path: /gift
    controller: App\Controller\EliteGiftController::showAction

restaurant:
    path: /restaurant
    controller: App\Controller\RestaurantController::showAction

books:
    path: /books
    controller: App\Controller\BooksController::showAction

gallery:
    path: /gallery
    controller: App\Controller\GalleryController::showAction


#gallery_by_category:
#    path: /gallery/category/{categorySlug}
#    controller: App\Controller\GalleryController::galleryByCategoryAction

gallery-by-catgory:
    path: /gallery/category/{categoryId}
    controller: App\Controller\GalleryController::galleryByCategoryAction
    options:
        expose: true