index:
    path: /
    controller: App\Controller\IndexController::showAction

painting_technique:
    path: /painting/technique
    controller: App\Controller\PaintingTechniqueController::showAction

elite_gift:
    path: /gift
    controller: App\Controller\EliteGiftController::showAction

restaurant:
    path: /restaurant
    controller: App\Controller\RestaurantController::showAction

books:
    path: /books
    controller: App\Controller\BooksController::showAction

gallery:
    path: /gallery
    controller: App\Controller\GalleryController::showAction

gallery_by_catgory:
    path: /gallery/category/{categoryId}
    controller: App\Controller\GalleryController::galleryByCategoryAction
    options:
        expose: true

send_contact:
    path: /contact
    controller: App\Controller\ContactController::sendContactAction
    methods: POST
    options:
        expose: true
